name: Main

on:
  push:
    branches: [main]
  pull_request:

jobs:
  format_and_lint_client_js:
    name: Format & Lint Client JS
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Format Client JS
        run: pnpm clients:js:format

      - name: Lint Client JS
        run: pnpm clients:js:lint

  format_and_lint_client_rust:
    name: Format & Lint Client Rust
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          toolchain: format, lint, test

      - name: Format Client Rust
        run: pnpm clients:rust:format

      - name: Lint Client Rust
        run: pnpm clients:rust:lint

      - name: Check Client Rust Features
        run: pnpm clients:rust:features

      - name: Check Client Rust 'rustdoc'
        run: pnpm clients:rust:rustdoc

  format_and_lint_interface:
    name: Lint Interface
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          toolchain: format, lint, test

      - name: Format
        run: pnpm zx ./scripts/interface/lint-format.mjs

      - name: Clippy
        run: pnpm zx ./scripts/interface/lint-clippy.mjs

      - name: Features
        run: pnpm zx ./scripts/interface/lint-features.mjs

      - name: Docs
        run: pnpm zx ./scripts/interface/lint-docs.mjs

  test_interface:
    name: Test Interface
    runs-on: ubuntu-latest
    needs: format_and_lint_interface
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          toolchain: test
          cargo-cache-key: cargo-interface
          solana: true

      - name: Test Interface
        run: pnpm interface:test

  generate_clients:
    name: Check Client Generation
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          toolchain: format

      - name: Generate Clients
        run: pnpm generate:clients

      - name: Check Working Directory
        run: |
          git status --porcelain
          test -z "$(git status --porcelain)"

  test_client_js:
    name: Test Client JS
    runs-on: ubuntu-latest
    needs: format_and_lint_client_js
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          solana: true

      - name: Test Client JS
        run: pnpm clients:js:test

  test_client_rust:
    name: Test Client Rust
    runs-on: ubuntu-latest
    needs: format_and_lint_client_rust
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          cargo-cache-key: cargo-rust-client
          solana: true

      - name: Test Client Rust
        run: pnpm clients:rust:test
